### PR TITLE
Ready: Fixes #15, Fixes #30

### LINKED ISSUE #15: Feature Request - Calculate Time duration on selected Text
It would be great, to have a feature to calculate the duration of the selected text...

Example:

I select this:
2016-11-25 12:03:50,659 WARN  [org.pentaho.platform.web.http. ......
.....
....
2016-11-25 12:06:52,859 WARN  [org.pentaho.platform.web.http. ......

Then the tool would show me in the status bar:
Selected: 3 Minutes, 2 Seconds, 200ms

This would be good for performance analysis.

So you have to search the first timestamp text at start of selection and the last one. Then calculate the difference and show it in the status bar.

### LINKED ISSUE #29: log.type should be log.exceptiontype
Wrong token name for exception type names...

### LINKED ISSUE #30: Milliseconds are not colored in time strings
Example:
`00:00:04.4010087`
`00:00:04,4010087`

### PR DESCRIPTION
**Pull request by HaaLeo**
### Removed 
* The maximum amount of digits for milliseconds is no longer limited. (Fixes #30)
### Feature
* Added time calculation of users selection. If the user selects multiple lines, the status bar shows which time period is selected. Check out [this sample](https://github.com/HaaLeo/vscode-logfile-highlighter#visualization-of-time-duration). (Fixes #15)

### CODE REVIEW

**Comment by emilast** [comment]
Hi and thanks for helping out! I'll try to test your changes later, so just tell me when you're done. I'm also not familiar with how to set up development environment with launch settings and all, so if you can give me some hints on how to test your code, I'll be most grateful :-)

**Comment by HaaLeo** [comment]
Hi emilast,
I give you a brief update what I have done so far.

### What I have done
I mainly followed microsoft's [word counter example](https://code.visualstudio.com/docs/extensions/example-word-count). So I used their [extension generator](https://code.visualstudio.com/docs/extensions/yocode) to set up the development environment and instead of counting words I calculate the time period of the log entries.

### Development environment
The basic set up can be done with previously mentioned extension generator. It adds all the launch and compile settings. To get familiar with it I recommend to try out the [extension generator](https://code.visualstudio.com/docs/extensions/yocode) and explore the first examples ([first](https://code.visualstudio.com/docs/extensions/example-hello-world) & [second](https://code.visualstudio.com/docs/extensions/example-word-count)).

### How to test the code
In order to test and review what I have done so far, you need [nodejs](https://nodejs.org/en/download/) and `npm` (node package manager) installed. After that 
1. Check out my repository
2. Open a command prompt in the root directory and run `npm install`
3. Open the root direcotry in Visual Studio Code and hit <kbd>F5</kbd> or select *Go* -> *Go to File...* and then typ in `Debug Extension` and hit  <kbd>Enter</kbd>

This should cause you to start a new instance of vs code with the extension running.  
Further information concerning running and debugging an extension can be found [here](https://code.visualstudio.com/docs/extensions/debugging-extensions#_running-and-debugging-your-extension) and the following sections.  

I will let you know when I am done with this feature and it is ready to be merged via a comment or something similar.

**Comment by HaaLeo** [comment]
Hi @emilast, 
the feature is now implemented and ready to be merged. I updated the pull requests description and my previous comment. 
If you have any suggestions or comments, just let me know.

**Comment by emilast** [comment]
Thanks! I'll try to have a look at it this weekend but can't promise it. Judging by your commit messages and documentation I above, I don't expect any problems :-)

**Comment by emilast** [comment]
@HaaLeo, I have tested your pull request now and it looks great! I'll definitely merge it when we're done, the feature you've implemented works great and will be super useful. Thanks also for incorporating all the Typescript infrastructure, it will be much easier to implement new features now.

One question, though. I'm having trouble running the unit and integration tests:

```
PS C:\code\vscode\vscode-logfile-highlighter - haaleo> npm run unittest

> LogFileHighlighter@1.2.0 unittest C:\code\vscode\vscode-logfile-highlighter - haaleo
> node out/test/testRunner.js -c jasmine.unittest.json

C:\code\vscode\vscode-logfile-highlighter - haaleo\node_modules\jasmine\lib\jasmine.js:109
    if(configFilePath || e.code != 'MODULE_NOT_FOUND') { throw e; }
                                                         ^

Error: Cannot find module 'C:\code\vscode\vscode-logfile-highlighter - haaleo\out\test..\jasmine.unittest.json'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
[snip]
```
Seems to be a minor path problem, a missing slash in `\out\test..\jasmine.unittest.json'` by the looks of it. I have tried to see where the paths come from but I'm a bit out of my territory here... Can you have a look at it? I'll merge your PR when I get the tests working.

**Comment by HaaLeo** [comment]
@emilast, 
thank you for your feedback. I appreciate you like the feature.
Concerning the error: Unfortunately i cannot reproduce this error locally on my PC. I can run the tests without any problem using powershell as well as cmd. I think might **line 47** of the `testRunner.ts` causes the problem. Can you run the unittests via vscode? If yes, you maybe can debug line 46-48 of the testRunner.ts and can retrace how the path is built. Otherwise please add the following statements to line 48 of the `testRunner.ts` and run the unittests with `npm run unittest`:

            console.log('Command line config path: ' + process.argv[process.argv.indexOf('-c') + 1]);
            console.log('Process dir name: ' + path.dirname(process.argv[1]));
            console.log('Normalized process dir name (with ../../../): ' +
            path.normalize(path.dirname(process.argv[1]) + '../../../'));
            console.log('Final config path:' + configPath);

I hope I could help. If the error still occurs send me please the error message (with the added logging statements).
BR

**Comment by emilast** [comment]
Works now :-)

Great work, I'll merge your PR now and will release a new version shortly, crediting you for this new feature. Again, thanks for implementing this.

**Comment by HaaLeo** [comment]
You are welcome :-)  
Thanks for crediting.

**Pull request merged**
