### PR TITLE
Enables creating custom log level

### LINKED ISSUE #31: Unable to match the log level of android
Unable to match the log level of android.
image

### LINKED ISSUE #33: Enhancement Request: Custom log levels
Hi, great extension, thanks for supporting it.

I'm using the NodeJS Winston logging tool and it has some additional logging levels.

It would be great to be able to be able to specify additional log levels and other string tokens. I would, for example, like to be able to colour "Verbose" or "VERBOSE" in green.

### LINKED ISSUE #34: Add new keyword in log level
Hello,
I do the entity framework and in the log when a sql request fails, the word "Failed" is used.
Would it be possible to add this word into the log level?
Thank you.

### PR DESCRIPTION
**Pull request by HaaLeo**
## Changes
For a description of the feature please refer to [this readme](https://github.com/HaaLeo/vscode-logfile-highlighter/tree/Enable-Custom-Log-Level#custom-log-levels) file.

## Related Issues
* Fixes #31 
* Fixes #33
* Fixes #34

### CODE REVIEW

**Comment by emilast** [comment]
@HaaLeo, what's the state of this PR? Can I have a look and merge it if it seems to work?

**Comment by HaaLeo** [comment]
@emilast Yes you can go ahead and merge this PR if it works. I just added a minor change.

**Comment by emilast** [comment]
I've had a look at this PR now and I really appreciate the hours you're putting in to make this feature come alive. Very useful indeed. Before releasing a new version of the extension I will probably make a few small changes to the configuration, I hope you don't mind.

I want to try to make the configuration as consistent as possible with the custom token colors so I'll have to think this over a little bit. Maybe the optimal solution would be to state a token name for the custom log level (which doesn't need to be a log level at all BTW, could be any type of pattern) instead and color it using the builtin infrastructure in VS Code.

Something like this:

```
"logFileHighlighter.customLogLevels": [
	{
		"value": "Foo",
		"scope": "log.error"
	}
]
```
But I suspect this involves a bit more work, so I'll probably just settle with renaming the `value` and `color` fields to be unambigous.

Again, many thanks for implementing this useful feature.

**Comment by HaaLeo** [comment]
@emilast I do not exactly understand what you mean with the „token name“ and the built in vscode infrastructure. 
You mean a way to use the built in syntax highlighting mechanism, so we do not need to colorfy the entries ourselves programmatically? 
However sure you can go ahead and rename the entries in the configuration. But then also rename the corresponding entries in the updateConfig() method :)

**Comment by emilast** [comment]
Yes, that was a spontaneous idea after seeing your code, but I'll leave that for now. I'll create a new release this evening so we get this out but of course we can continue thinking out how to improve it later.

**Comment by HaaLeo** [comment]
Yes I agree that would be the most elegant approach. First I had something similar in mind, too. But I could not find a “syntax-api” or something similar that lets you define the syntax highlighting during runtime.

**Pull request merged**
